CREATE TABLE [dbo].[Notification]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [UserId] INT NOT NULL, 
    [Message] NVARCHAR(255) NOT NULL, 
	[Link] NVARCHAR(255) NOT NULL,
	[CreatedOn] DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    [Read] BIT NOT NULL
)
